version: '3'

services:
  graphql_db:
    container_name: graphql_db
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=phunt123!@#
    ports:
      - 3307:3306
    command: [mysqld, --character-set-server=utf8, --collation-server=utf8_unicode_ci]
    healthcheck:
      test: exit 0

  graphql_web:
    build:
      context: .
      args:
        tag: "2.5.3"
    container_name: graphql_web
    ports:
      - 3000:3000
    command: bundle exec rails s -b0
    links:
      - graphql_db
    depends_on:
      - graphql_db
    volumes:
      - ".:/root/graphql"
