default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: graphql_db
  username: root
  password: phunt123!@#
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: graphql_development
