default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: myapp_db
  username: root
  password: tinhokok
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: myapp_development
